// Use .mjs config to avoid temporary `vite.config.js.timestamp-*.mjs` files generated by Vite when bundling JS config.
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const configHorizonsViteErrorHandler = `
const observer = new MutationObserver((mutations) => {
	for (const mutation of mutations) {
		for (const addedNode of mutation.addedNodes) {
			if (
				addedNode.nodeType === Node.ELEMENT_NODE &&
				(
					addedNode.tagName?.toLowerCase() === 'vite-error-overlay' ||
					addedNode.classList?.contains('backdrop')
				)
			) {
				handleViteOverlay(addedNode);
			}
		}
	}
});

observer.observe(document.documentElement, {
	childList: true,
	subtree: true
});

function handleViteOverlay(node) {
	if (!node.shadowRoot) {
		return;
	}

	const backdrop = node.shadowRoot.querySelector('.backdrop');

	if (backdrop) {
		const overlayHtml = backdrop.outerHTML;
		const parser = new DOMParser();
		const doc = parser.parseFromString(overlayHtml, 'text/html');
		const messageBodyElement = doc.querySelector('.message-body');
		const fileElement = doc.querySelector('.file');
		const messageText = messageBodyElement ? messageBodyElement.textContent.trim() : '';
		const fileText = fileElement ? fileElement.textContent.trim() : '';
		const error = messageText + (fileText ? ' File:' + fileText : '');

		window.parent.postMessage({
			type: 'horizons-vite-error',
			error,
		}, '*');
	}
}
`;

const configHorizonsRuntimeErrorHandler = `
window.onerror = (message, source, lineno, colno, errorObj) => {
	const errorDetails = errorObj ? JSON.stringify({
		name: errorObj.name,
		message: errorObj.message,
		stack: errorObj.stack,
		source,
		lineno,
		colno,
	}) : null;

	window.parent.postMessage({
		type: 'horizons-runtime-error',
		message,
		error: errorDetails
	}, '*');
};
`;

const configHorizonsConsoleErrroHandler = `
const originalConsoleError = console.error;
console.error = function(...args) {
	originalConsoleError.apply(console, args);

	let errorString = '';

	for (let i = 0; i < args.length; i++) {
		const arg = args[i];
		if (arg instanceof Error) {
				errorString = arg.stack || (arg.name + ': ' + arg.message);
			break;
		}
	}

	if (!errorString) {
		errorString = args.map(arg => typeof arg === 'object' ? JSON.stringify(arg) : String(arg)).join(' ');
	}

	window.parent.postMessage({
		type: 'horizons-console-error',
		error: errorString
	}, '*');
};
`;

const configWindowFetchMonkeyPatch = `
const originalFetch = window.fetch;

window.fetch = function(...args) {
	const url = args[0] instanceof Request ? args[0].url : args[0];

	if (url.startsWith('ws:') || url.startsWith('wss:')) {
		return originalFetch.apply(this, args);
	}

	return originalFetch.apply(this, args)
		.then(async response => {
			const contentType = response.headers.get('Content-Type') || '';

			const isDocumentResponse =
				contentType.includes('text/html') ||
				contentType.includes('application/xhtml+xml');

			if (!response.ok && !isDocumentResponse) {
					const responseClone = response.clone();
					const errorFromRes = await responseClone.text();
					const requestUrl = response.url;
					console.error('Fetch error from ' + requestUrl + ': ' + errorFromRes);
			}

			return response;
		})
		.catch(error => {
			if (!url.match(/\.html?$/i)) {
				console.error(error);
			}

			throw error;
		});
};
`;

const configNavigationHandler = `
if (window.navigation && window.self !== window.top) {
	window.navigation.addEventListener('navigate', (event) => {
		const url = event.destination.url;

		try {
			const destinationUrl = new URL(url);
			const destinationOrigin = destinationUrl.origin;
			const currentOrigin = window.location.origin;

			if (destinationOrigin === currentOrigin) {
				return;
			}
		} catch (error) {
			return;
		}

		window.parent.postMessage({
			type: 'horizons-navigation-error',
			url,
		}, '*');
	});
}
`;

function createHorizonDevOverlayPlugin() {
  return {
    name: 'add-transform-index-html',
    apply: 'serve',
    transformIndexHtml(html) {
      const tags = [
        { tag: 'script', attrs: { type: 'module' }, children: configHorizonsRuntimeErrorHandler, injectTo: 'head' },
        { tag: 'script', attrs: { type: 'module' }, children: configHorizonsViteErrorHandler, injectTo: 'head' },
        { tag: 'script', attrs: { type: 'module' }, children: configHorizonsConsoleErrroHandler, injectTo: 'head' },
        { tag: 'script', attrs: { type: 'module' }, children: configWindowFetchMonkeyPatch, injectTo: 'head' },
        { tag: 'script', attrs: { type: 'module' }, children: configNavigationHandler, injectTo: 'head' },
      ];

      return { html, tags };
    },
  };
}

function createTemplateBannerPlugin() {
  return {
    name: 'template-banner-script',
    apply: 'build',
    transformIndexHtml(html) {
      if (!process.env.TEMPLATE_BANNER_SCRIPT_URL || !process.env.TEMPLATE_REDIRECT_URL) {
        return html;
      }

      return {
        html,
        tags: [
          {
            tag: 'script',
            attrs: {
              src: process.env.TEMPLATE_BANNER_SCRIPT_URL,
              'template-redirect-url': process.env.TEMPLATE_REDIRECT_URL,
            },
            injectTo: 'head',
          },
        ],
      };
    },
  };
}

// Visual tooling is explicitly opt-in to keep dev/build startup stable.

export default defineConfig(({ command }) => {
  // Keep config resolution synchronous so `npm run dev` does not pay async/dynamic-import overhead on every startup.
  const enableVisualEditor = false;
  const enableHorizonDevOverlay = false;

  const visualEditorPlugins = [];
  if (enableVisualEditor) {
    if (enableHorizonDevOverlay) {
      visualEditorPlugins.push(createHorizonDevOverlayPlugin());
    }
  }

  const enableTemplateBanner = command === 'build'
    && process.env.VITE_ENABLE_TEMPLATE_BANNER === 'true'
    && process.env.TEMPLATE_BANNER_SCRIPT_URL
    && process.env.TEMPLATE_REDIRECT_URL;

  const buildOnlyPlugins = enableTemplateBanner ? [createTemplateBannerPlugin()] : [];

  return {
    plugins: [
      ...visualEditorPlugins,
      react(),
      ...buildOnlyPlugins,
    ],
    cacheDir: 'node_modules/.vite',
    server: {
      cors: true,
      headers: {
        'Cross-Origin-Embedder-Policy': 'credentialless',
      },
      allowedHosts: true,
      watch: {
        // Restrict chokidar to only directories relevant to the frontend.
        // Without this, Vite watches backend/, plugins/, tools/, tests/ —
        // wasting inotify instances and generating HMR noise on every
        // server-side file change. Each watched dir = 1 inotify instance;
        // the system default limit (128) gets exhausted quickly when
        // git, npm, and vite run concurrently, causing >10s lags.
        ignored: [
          '**/node_modules/**',
          '**/.git/**',
          '**/backend/**',
          '**/plugins/**',
          '**/tools/**',
          '**/tests/**',
        ],
      },
    },
    resolve: {
      extensions: ['.jsx', '.js', '.tsx', '.ts', '.json'],
      alias: {
        '@': path.resolve(__dirname, './src'),
      },
    },
    optimizeDeps: {
      exclude: ['@babel/parser', '@babel/traverse', '@babel/generator', '@babel/types'],
    },
    build: {
      rollupOptions: {
        external: [
          '@babel/parser',
          '@babel/traverse',
          '@babel/generator',
          '@babel/types',
        ],
      },
    },
  };
});
